development:
  adapter: postgresql
  host: localhost
  username: chirrup
  password: chirrup
  database: chirrup_dev

test:
  adapter: postgresql
  host: localhost
  username: chirrup
  password: chirrup
  database: chirrup_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: daj33vp4vd5v2u
  username: cswschfyihldoq
  host: ec2-107-20-165-44.compute-1.amazonaws.com
  port: 5432